Install Minio

diff --git a/.github/workflows/performance_testing_large_aws.yml b/.github/workflows/performance_testing_large_aws.yml
--- a/.github/workflows/performance_testing_large_aws.yml
+++ b/.github/workflows/performance_testing_large_aws.yml
@@ -2,73 +2,74 @@ name: Large-Sized Performance Testing AWS
 
 on:
   workflow_dispatch:
+  push:
 
 env:
   ENVIRONMENT_NAME: performance-testing-large-amd64
 
 jobs:
 
-  build-core:
-    runs-on: heavyweight-generic-jobs
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.PAT }}
-          submodules: recursive
- 
-      - name: Set up Docker Buildx
-        id: buildx
-        uses: docker/setup-buildx-action@v3
-  
-      - name: Login to ghcr.io container registry
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: plauth
-          password: ${{ secrets.PAT }}
-   
-      - name: Build and push the Docker image
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          file: Dockerfile
-          platforms: linux/amd64
-          tags: ghcr.io/ultihash/cluster:${{ env.ENVIRONMENT_NAME }}
-          push: true
+ # build-core:
+ #   runs-on: heavyweight-generic-jobs
+ #   steps:
+ #     - uses: actions/checkout@v4
+ #       with:
+ #         token: ${{ secrets.PAT }}
+ #         submodules: recursive
+ #
+ #     - name: Set up Docker Buildx
+ #       id: buildx
+ #       uses: docker/setup-buildx-action@v3
+ # 
+ #     - name: Login to ghcr.io container registry
+ #       uses: docker/login-action@v2
+ #       with:
+ #         registry: ghcr.io
+ #         username: plauth
+  #        password: ${{ secrets.PAT }}
+  # 
+  #    - name: Build and push the Docker image
+  #      uses: docker/build-push-action@v5
+  #      with:
+  #        context: .
+  #        file: Dockerfile
+  #        platforms: linux/amd64
+  #        tags: ghcr.io/ultihash/cluster:${{ env.ENVIRONMENT_NAME }}
+  #        push: true
 
-  build-database-init:
-    runs-on: lightweight-generic-jobs
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          token: ${{ secrets.PAT }}
-          submodules: recursive
-  
-      - name: Set up Docker Buildx
-        id: buildx
-        uses: docker/setup-buildx-action@v3
-  
-      - name: Login to ghcr.io container registry
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: plauth
-          password: ${{ secrets.PAT }}
-   
-      - name: Build and push the Docker image
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          file: tools/database-init/Dockerfile
-          platforms: linux/amd64
-          tags: ghcr.io/ultihash/database-init:${{ env.ENVIRONMENT_NAME }}
-          push: true
+  #build-database-init:
+  #  runs-on: lightweight-generic-jobs
+  #  steps:
+  #    - uses: actions/checkout@v4
+  #      with:
+  #        token: ${{ secrets.PAT }}
+  #        submodules: recursive
+  #
+  #    - name: Set up Docker Buildx
+  #      id: buildx
+  #      uses: docker/setup-buildx-action@v3
+ # 
+ #     - name: Login to ghcr.io container registry
+ #       uses: docker/login-action@v2
+ #       with:
+ #         registry: ghcr.io
+ #         username: plauth
+ #         password: ${{ secrets.PAT }}
+ #  
+ #     - name: Build and push the Docker image
+ #       uses: docker/build-push-action@v5
+ #       with:
+ #         context: .
+ #         file: tools/database-init/Dockerfile
+ #         platforms: linux/amd64
+ #         tags: ghcr.io/ultihash/database-init:${{ env.ENVIRONMENT_NAME }}
+ #         push: true
 
   deploy-and-test:
     runs-on: lightweight-generic-jobs
-    needs: 
-      - build-core
-      - build-database-init
+  #  needs: 
+  #    - build-core
+  #    - build-database-init
     steps:
 
       - uses: actions/checkout@v4
@@ -104,6 +105,7 @@ jobs:
       - name: Delete the testing environment if exists
         run: |
           helm uninstall ${{ env.ENVIRONMENT_NAME }} -n ${{ env.ENVIRONMENT_NAME }} --wait || true
+          helm uninstall minio -n ${{ env.ENVIRONMENT_NAME }} --wait || true
           kubectl delete pods --all --force -n ${{ env.ENVIRONMENT_NAME }} || true
           kubectl delete pvc --all --force -n ${{ env.ENVIRONMENT_NAME }} || true
           kubectl delete secrets --all -n ${{ env.ENVIRONMENT_NAME }} || true
@@ -152,57 +154,69 @@ jobs:
           input: performance-testing/large/ultihash-helm-values.yaml
           output: ultihash-helm-values.yaml
       
-      - name: Download the data corpora to the tester machine
-        run: |
-          bash performance-testing/execute_job.sh s3-data-downloader.yaml s3-data-downloader ${{ env.ENVIRONMENT_NAME }} 1h
+      #- name: Download the data corpora to the tester machine
+      #  run: |
+      #    bash performance-testing/execute_job.sh s3-data-downloader.yaml s3-data-downloader ${{ env.ENVIRONMENT_NAME }} 1h
           
-      - name: Install the UltiHash cluster
-        run: |
-          echo '${{ secrets.REGISTRY_USER }}' | helm registry login registry.ultihash.io -u github --password-stdin
-          helm install ${{ env.ENVIRONMENT_NAME }} oci://registry.ultihash.io/stable/ultihash-cluster -n ${{ env.ENVIRONMENT_NAME }} --values ultihash-helm-values.yaml --wait --timeout 15m
-          sleep 180
+      #- name: Install the UltiHash cluster
+      #  run: |
+      #    echo '${{ secrets.REGISTRY_USER }}' | helm registry login registry.ultihash.io -u github --password-stdin
+      #    helm install ${{ env.ENVIRONMENT_NAME }} oci://registry.ultihash.io/stable/ultihash-cluster -n ${{ env.ENVIRONMENT_NAME }} --values ultihash-helm-values.yaml --wait --timeout 15m
+      #    sleep 180
 
-      - name: Execute the performance test against UltiHash
+      #- name: Execute the performance test against UltiHash
+      #  run: |
+      #    bash performance-testing/execute_job.sh performance-tester-ultihash.yaml performance-tester ${{ env.ENVIRONMENT_NAME }} 1h
+
+      # Here should be a clean up job
+
+      - name: Install the MinIO cluster 
         run: |
-          bash performance-testing/execute_job.sh performance-tester-ultihash.yaml performance-tester ${{ env.ENVIRONMENT_NAME }} 1h
+          helm repo add bitnami https://charts.bitnami.com/bitnami
+          helm repo update bitnami
+          helm install minio bitnami/minio -n ${{ env.ENVIRONMENT_NAME }} --values performance-testing/large/minio-helm-values.yaml --version 14.6.22 --wait --timeout 15m
+
+      #- name: Execute the performance test against MinIO
+      #  run: |
+      #    bash performance-testing/execute_job.sh performance-tester-minio.yaml performance-tester ${{ env.ENVIRONMENT_NAME }} 1h
  
-  cleanup:
-    runs-on: lightweight-generic-jobs
-    needs: deploy-and-test
-    if: ${{ always() }}
-    steps:
-
-      - name: Install AWS CLI
-        uses: unfor19/install-aws-cli-action@v1
-        with:
-          version: 2
-          arch: amd64
-
-      - name: Setup the AWS credentials
-        run: |
-          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY}}" >> $GITHUB_ENV
-          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY}}" >> $GITHUB_ENV
-          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV
-
-      - uses: azure/setup-kubectl@v3
-        with:
-          version: v1.28.7
-
-      - name: Download Kubeconfig
-        run: |
-          mkdir ~/.kube
-          aws eks update-kubeconfig --name aws-core
-    
-      - uses: azure/setup-helm@v4.0.0
-        with:
-         version: v3.14.0
-
-      - name: Environment cleanup
-        run: |
-          helm uninstall ${{ env.ENVIRONMENT_NAME }} -n ${{ env.ENVIRONMENT_NAME }} --wait || true
-          kubectl delete pods --all --force -n ${{ env.ENVIRONMENT_NAME }} || true
-          kubectl delete pvc --all --force -n ${{ env.ENVIRONMENT_NAME }} || true
-          kubectl delete secrets --all -n ${{ env.ENVIRONMENT_NAME }} || true
-          kubectl delete ns ${{ env.ENVIRONMENT_NAME }} || true
-        continue-on-error: true
+  #cleanup:
+  #  runs-on: lightweight-generic-jobs
+  #  needs: deploy-and-test
+  #  if: ${{ always() }}
+  #  steps:
+#
+#      - name: Install AWS CLI
+#        uses: unfor19/install-aws-cli-action@v1
+#        with:
+#          version: 2
+#          arch: amd64
+#
+#      - name: Setup the AWS credentials
+#        run: |
+#          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY}}" >> $GITHUB_ENV
+#          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY}}" >> $GITHUB_ENV
+#          echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV
+#
+#      - uses: azure/setup-kubectl@v3
+#        with:
+#          version: v1.28.7
+#
+#      - name: Download Kubeconfig
+#        run: |
+#          mkdir ~/.kube
+#          aws eks update-kubeconfig --name aws-core
+#    
+#      - uses: azure/setup-helm@v4.0.0
+#        with:
+#         version: v3.14.0
+#
+#      - name: Environment cleanup
+#        run: |
+#          helm uninstall ${{ env.ENVIRONMENT_NAME }} -n ${{ env.ENVIRONMENT_NAME }} --wait || true
+#          kubectl delete pods --all --force -n ${{ env.ENVIRONMENT_NAME }} || true
+#          kubectl delete pvc --all --force -n ${{ env.ENVIRONMENT_NAME }} || true
+#          kubectl delete secrets --all -n ${{ env.ENVIRONMENT_NAME }} || true
+#          kubectl delete ns ${{ env.ENVIRONMENT_NAME }} || true
+#        continue-on-error: true
       
